plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'net.darkhax.curseforgegradle'
    id 'com.modrinth.minotaur'
}

neoForge {
    version = neoforge_version

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            clientData()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources. def fullModId
            def fullModId = "${project.mod_id}${project.intdyn_id}"
            programArguments.addAll '--mod', fullModId, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()

        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories { //all of these are for adding crates compat
    mavenLocal()
    maven {
        name = 'Curse Maven'
        url = 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven { url 'https://maven.blamejared.com' }
    maven {
        url = "https://maven.theillusivec4.top/"
    }
}
dependencies {
    // compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    implementation("curse.maven:apple-crates-630726:${apple_crates_file}")
    //mods
    runtimeOnly("curse.maven:integrated-dynamics-236307:${intdyn_file}")
    runtimeOnly("curse.maven:cyclops-core-232758:${cyclops_file}")
    runtimeOnly("curse.maven:common-capabilities-247007:${common_cap_file}")
}




tasks.register('publishCurseForge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {

    apiToken = findProperty('cf_api_token')

    // The main file to upload
    def mainFile = upload(cf_intdyn, jar)
    mainFile.releaseType = 'release'
    mainFile.changelog = "${changelog}"
    mainFile.changelogType = 'markdown'
    mainFile.addJavaVersion('Java 17')
    mainFile.addRequirement('apple-crates')
    mainFile.addRequirement('integrated-dynamics')
    mainFile.addModLoader('neoforge')
}

modrinth {
    token.set(project.findProperty('modrinth_api_token'))
    projectId.set(modrinth_intdyn)
    changelog = "${changelog}"
    versionName.set("${intdyn}-NeoForge-${minecraft_version}-$version")
    versionType.set("${releasetype}")
    uploadFile.set(tasks.jar)
    loaders = ["neoforge"]
    gameVersions = ["${minecraft_version}"]
}