plugins {
    id 'idea'
    id 'fabric-loom' version '1.11-SNAPSHOT' apply(false)
    id 'net.neoforged.moddev.legacyforge' version '2.0.77' apply(false)
}

// apply java 17 as base language instead of j21, which is requiered for loom 11
tasks.withType(JavaCompile).configureEach {
    it.options.release.set("${java_version}")
}
subprojects {
    apply plugin: 'java-library'
    project.group = rootProject.group
    project.version = rootProject.version
    java {
        toolchain.languageVersion = JavaLanguageVersion.of(java_version)
        withSourcesJar()
        withJavadocJar()
    }
}