# Project
version=3.0.0
group=absolemjackdaw
changelog=1.20.1 update
java_version=17

# Common
minecraft_version=1.20.1
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server
license=MIT
credits=''
description=Sell your stuff in fancy crates! support for 
minecraft_version_range=[1.20.1, 1.22)
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Forge
forge_version=47.3.0
forge_loader_version_range=[47,)
//forge_ats_enabled=true

# Fabric
fabric_version=0.92.2+1.20.1
fabric_loader_version=0.16.9

# Mod options
mod_name=Apple Crate Addon
mod_author=Absolem Jackdaw
mod_id=applecrates_

# Gradle
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

terrablender_file=5378180
patchouli_file=6164575
curios_file=6058834
# fruitful fun
kiwi_file=6184688
# fruitful fun, double dep
lychee_file=6188573
cyclops_file=6199446
common_cap_file=5980078
lodestone_file=5929869
#mantle_file=5339977
valhelsia_file=5189548


apple_crates_file=6207428
#byg_file=3970266
bop_file=6028852
forbarc_file=5198323
#premwood_file=3905203
intdyn_file=6171347
botania_file=6172172
fruit_file=6203392
malum_file=5929596
enl_end_file=4880586
solar_file=5255888
#tcon_file=5735113

bop=Plenty Crates
botania=Botanical Crates
byg=Byg Crates
pw=Premium Crates
forbarc=Forbidden Crates
tcon=Construct Crates
nourishedend =Enlightened Crates
malum =Malumian Crates
fruit =Fruit Crates
solar =Solar Crates
intdyn =Dynamic Crates

byg_id=byg
bop_id=bop
bot_id=botania
intdyn_id=intdyn
prem_id=premwood
solar_id=solarforge
fruit_id=fruit
malum_id=malum
eend_id=nourishedend
tcon_id=tcon
forbarc_id=forbarc