# Project
version=3.3.1
group=absolemjackdaw
changelog=Update to latest applecrate API.
java_version=17
# Common
minecraft_version=1.20.1
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server
license=MIT
credits=''
mod_description=Sell your stuff in fancy crates! support for
minecraft_version_range=[1.20.1, 1.22)
parchment_minecraft=1.20.1
parchment_version=2023.09.03
# Forge
forge_version=47.4.0
forge_loader_version_range=[47,)
//forge_ats_enabled=true
# Fabric
fabric_version=0.92.6+1.20.1
fabric_loader_version=0.17.2
# Mod options
mod_name=Apple Crate Addon
mod_author=Absolem Jackdaw
mod_id=applecrates_
# Gradle
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

#dependency files
terrablender_file=5378180
terrablender_file_fabric=6290449
glitchcore_file=5787839
glitchcore_file_fabric=5787838
patchouli_file=6164575
curios_file=6058834
# fruitful fun
kiwi_file=6184688
kiwi_file_fabric=6466894
# fruitful fun, double dep
lychee_file=6188573
lychee_file_fabric=7017489
cyclops_file=6199446
common_cap_file=5980078
lodestone_file=5929869
lodestone_file_fabric=6070172
mantle_file=6819217
valhelsia_file=5189548
corgilib=6002849
corgilib_fabric=6002847
ohthetreesyoullgrow=6608610
ohthetreesyoullgrow_fabric=6608608
geckolib=7017796
geckolib_fabric=6027561

#mod files
apple_crates_file=7011810
apple_crates_file_fabric=7022116
byg_file=6943503
byg_file_fabric=6943501
bop_file=6364065
bop_file_fabric=6364066
forbarc_file=5198323
#premwood_file=3905203
intdyn_file=6171347
botania_file=6172172
fruit_file=6203392
fruit_file_fabric=7011135
malum_file=5929596
malum_file_fabric=5929596
enl_end_file=4880586
solar_file=5255888
tcon_file=6777068
tfc_file=6990923

#mod names
bop=Plenty Crates
botania=Botanical Crates
byg=Byg Crates
pw=Premium Crates
forbarc=Forbidden Crates
tcon=Construct Crates
nourishedend=Enlightened Crates
malum=Malumian Crates
fruit=Fruit Crates
solar=Solar Crates
intdyn=Dynamic Crates
tfc=Terra Firma Craft

#mod ids
byg_id=byg
bop_id=bop
bot_id=botania
intdyn_id=intdyn
prem_id=premwood
solar_id=solarforge
fruit_id=fruit
malum_id=malum
eend_id=nourishedend
tcon_id=tcon
forbarc_id=forbarc
tfc_id=tfc