# Project
version=9.0.0
group=absolemjackdaw
changelog=update to 1.21.11
java_version=21
releasetype=release
# Common
minecraft_version=1.21.11
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server
license=MIT
credits=''
mod_description=Sell your stuff in fancy crates! support for
minecraft_version_range=[1.21.11, 1.22)
parchment_minecraft=1.21.10
parchment_version=2025.10.12
neo_form_version=1.21.11-20251209.172050
# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)
# NeoForge
neoforge_version=21.11.17-beta
neoforge_loader_version_range=[4,)
# Fabric
fabric_version=0.140.2+1.21.11
fabric_loader_version=0.18.4
# Mod options
mod_name=Apple Crate Addon
mod_author=Absolem Jackdaw
mod_id=applecrates_
# Gradle
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

#dependency files
terrablender_file=21.11.0.0
terrablender_file_fabric=21.11.0.0
glitchcore_file=7335721
glitchcore_file_fabric=7335722
patchouli_file=
curios_file=
# fruitful fun
kiwi_file=
kiwi_file_fabric=
# fruitful fun, double dep
lychee_file=
lychee_file_fabric=
cyclops_file=7407550
cyclops_file_fabric=7407548
common_cap_file=7407741
lodestone_file=
lodestone_file_fabric=
mantle_file=
valhelsia_file=
valhelsia_file_fabric=
corgilib=7386252
corgilib_fabric=7386250
ohthetreesyoullgrow=7363818
ohthetreesyoullgrow_fabric=7363759
geckolib=7405440
geckolib_fabric=7405431

#mod files
apple_crates_file=7392151
apple_crates_file_fabric=7392150
azalea_file=
byg_file=7386826
byg_file_fabric=7386824
bop_file=7403572
bop_file_fabric=7403573
forbarc_file=
intdyn_file=7407748
botania_file=
fruit_file=
fruit_file_fabric=
malum_file=
enl_end_file=
solar_file=
tcon_file=
tfc_file=

#mod names
azalea=Azalea Crates
bop=Plenty Crates
botania=Botanical Crates
byg=Byg Crates
pw=Premium Crates
forbarc=Forbidden Crates
tcon=Construct Crates
nourishedend=Enlightened Crates
malum=Malumian Crates
fruit=Fruit Crates
solar=Solar Crates
intdyn=Dynamic Crates
tfc=Terra Firma Craft

#mod ids
azalea_id=azalea
byg_id=byg
bop_id=bop
bot_id=botania
intdyn_id=intdyn
prem_id=premwood
solar_id=solarforge
fruit_id=fruit
malum_id=malum
eend_id=nourishedend
tcon_id=tcon
forbarc_id=forbarc
tfc_id=tfc

#release info
modrinth_byg=amJBWyKu
cf_byg=669657
modrinth_bop=e7ssudHs
cf_bop=669343
modrinth_intdyn=F89QlKGh
cf_intdyn=670316