pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Sponge Snapshots'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

// This should match the folder name of the project, or else IDEA may complain (see https://youtrack.jetbrains.com/issue/IDEA-317606)
rootProject.name = 'AppleCrateAddons'
include("common")
include("fabric")
include("forge")

include("forge_botanicalcrates")
//libraries are broken in 1.20.1, i cant get them to work.
//include("forge_bygcrates")
include("fabric_bygcrates")
include("forge_dyncrates")
include("forge_enlightendcrates")
include("forge_firmacrates")
include("forge_forbiddencrates")
include("forge_fruitcrates")
include("fabric_fruitcrates")
include("forge_malumiancrates")
include("forge_plentycrates")
include("fabric_plentycrates")
//include("forge_premiumcrates")
include("forge_solarcrates")
include("forge_tconcrates")