pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Fabric'
                    url = uri('https://maven.fabricmc.net')
                }
            }
            filter {
                includeGroup('net.fabricmc')
                includeGroup('fabric-loom')
            }
            //1.11 loom
            maven {
                // e.g. the “stellardrift” internal maven for unpick
                url = uri("https://repo.stellardrift.ca/maven/internal/")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Sponge'
                    url = uri('https://repo.spongepowered.org/repository/maven-public')
                }
            }
            filter {
                includeGroupAndSubgroups("org.spongepowered")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Forge'
                    url = uri('https://maven.minecraftforge.net')
                }
            }
            filter {
                includeGroupAndSubgroups('net.minecraftforge')
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

// This should match the folder name of the project, or else IDEA may complain (see https://youtrack.jetbrains.com/issue/IDEA-317606)
rootProject.name = 'AppleCrateAddons'
include("common")

//include("forge_azaleacrates")
//include("forge_botanicalcrates")
include("forge_bygcrates")
include("fabric_bygcrates")
include("forge_dyncrates")
//include("forge_enlightendcrates")
//include("forge_firmacrates")
//include("forge_forbiddencrates")
//include("forge_fruitcrates")
//include("fabric_fruitcrates")
//include("forge_malumiancrates")
include("forge_plentycrates")
include("fabric_plentycrates")
//include("forge_premiumcrates")
//include("forge_solarcrates")
//include("forge_tconcrates")