modLoader = "javafml" #mandatory

loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license = "gnu v3"

issueTrackerURL = "https://github.com/ArtixAllMighty/AppleCrates/issues" #optional

[[mods]] #mandatory

modId = "applecrates_malum" #mandatory

version = "${file.jarVersion}" #mandatory

displayName = "Apple Crates for Malum" #mandatory

displayURL = "https://www.curseforge.com/minecraft/mc-mods/apple-crates" #optional

logoFile = "logo.png" #optional

authors = "Absolem Jackdaw" #optional

description = '''
Sell your stuff in fancy crates! support for Malum
'''

[[dependencies.applecrates_malum]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering="AFTER"
side = "BOTH"
[[dependencies.applecrates_malum]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering="AFTER"
side = "BOTH"
[[dependencies.applecrates_malum]]
modId = "applecrates"
mandatory = true
versionRange = "[2.7,)"
ordering="AFTER"
side = "SERVER"
[[dependencies.applecrates_malum]]
modId = "malum"
mandatory = true
versionRange = "[0,)"
ordering="AFTER"
side = "BOTH"