modLoader = "javafml" #mandatory

loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license = "gnu v3"

issueTrackerURL = "https://github.com/ArtixAllMighty/AppleCrates/issues" #optional

[[mods]] #mandatory

modId = "applecrates_fruit" #mandatory

version = "${file.jarVersion}" #mandatory

displayName = "Apple Crates for Fruit Trees" #mandatory

displayURL = "https://www.curseforge.com/minecraft/mc-mods/apple-crates" #optional

logoFile= "logo.png" #optional

authors = "Absolem Jackdaw" #optional

description = '''
Sell your stuff in fancy crates! support for Fruit Trees
'''

[[dependencies.applecrates_fruit]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering="AFTER"
side = "BOTH"
[[dependencies.applecrates_fruit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering="AFTER"
side = "BOTH"
[[dependencies.applecrates_fruit]]
modId = "applecrates"
mandatory = true
versionRange = "[1.6,)"
ordering="AFTER"
side = "SERVER"
[[dependencies.applecrates_fruit]]
modId = "fruittrees"
mandatory = true
versionRange = "[0,)"
ordering="AFTER"
side = "BOTH"