modLoader = "javafml" #mandatory

loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license = "gnu v3"

issueTrackerURL = "https://github.com/ArtixAllMighty/AppleCrates/issues" #optional

[[mods]] #mandatory

modId = "applecrates_forbarc" #mandatory

version = "${file.jarVersion}" #mandatory

displayName = "Apple Crates for Forbidden Arcanus" #mandatory

displayURL = "https://www.curseforge.com/minecraft/mc-mods/apple-crates" #optional

logoFile = "logo.png" #optional

authors = "Absolem Jackdaw" #optional

description = '''
Sell your stuff in fancy crates! support for Forbidden Arcanus
'''

[[dependencies.applecrates_forbarc]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering="AFTER"
side = "BOTH"
[[dependencies.applecrates_forbarc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering="AFTER"
side = "BOTH"
[[dependencies.applecrates_forbarc]]
modId = "applecrates"
mandatory = true
versionRange = "[2,)"
ordering="AFTER"
side = "SERVER"